#pragma once

#include "libmx.h"
#include <complex.h>
#include <errno.h>
#include <sys/types.h>
#include <ctype.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <stdio.h>
#include <stddef.h>
#include <string.h>
#include <signal.h>
#include <limits.h>
#include <termios.h>
#include <sys/stat.h>
#include <spawn.h>
#include <libgen.h>
#include <wordexp.h>
